const PAGE_STYLE = `
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 700px; margin: 40px auto; padding: 0 20px; color: #1B4332; line-height: 1.7; }
    h1 { color: #2D6A4F; } h2 { color: #2D6A4F; margin-top: 28px; } h3 { color: #2D6A4F; } a { color: #2D6A4F; }
  </style>`;

const PRIVACY = `<!DOCTYPE html><html><head><title>Privacy Policy – AI Caddie</title>${PAGE_STYLE}</head><body>
<h1>Privacy Policy</h1>
<p><strong>Last updated:</strong> March 3, 2026</p>
<p>AI Caddie ("we", "our", "the app") is committed to protecting your privacy. This policy explains what data we collect and how we use it.</p>
<h2>Data We Collect</h2>
<ul>
<li><strong>Account information:</strong> Your email address and a securely hashed password when you create an account.</li>
<li><strong>Club distances:</strong> The average yardages you enter for each club in your bag.</li>
<li><strong>Round data:</strong> Course names, scores, fairway/GIR stats, and notes you log during rounds.</li>
<li><strong>Subscription status:</strong> We store your subscription expiration date to manage access to premium features.</li>
</ul>
<h2>How We Use Your Data</h2>
<ul>
<li>To provide personalized club recommendations and course strategy powered by AI.</li>
<li>To save and display your round history and statistics.</li>
<li>To manage your subscription and account.</li>
</ul>
<h2>Third-Party Services</h2>
<ul>
<li><strong>Anthropic (Claude AI):</strong> Your club distances are sent to generate recommendations. No personal identifiers are included.</li>
<li><strong>Apple App Store:</strong> Subscription transactions are verified through Apple's StoreKit API.</li>
</ul>
<h2>Data Retention &amp; Deletion</h2>
<p>You can delete your account at any time from the Profile tab in the app. This permanently removes all your data including rounds, clubs, and account information.</p>
<h2>Security</h2>
<p>Passwords are hashed using bcrypt. All communication uses HTTPS encryption.</p>
<h2>Contact</h2>
<p>Questions? Email us at <a href="mailto:support@caiddie.com">support@caiddie.com</a>.</p>
</body></html>`;

const TERMS = `<!DOCTYPE html><html><head><title>Terms of Use – AI Caddie</title>${PAGE_STYLE}</head><body>
<h1>Terms of Use</h1>
<p><strong>Last updated:</strong> March 3, 2026</p>
<h2>Acceptance</h2>
<p>By using AI Caddie you agree to these terms. If you do not agree, do not use the app.</p>
<h2>The Service</h2>
<p>AI Caddie provides AI-powered golf club recommendations, course strategy, and round tracking. Recommendations are generated by artificial intelligence and should be used as guidance only — they do not guarantee improved performance.</p>
<h2>Subscriptions</h2>
<ul>
<li>Some features require a paid monthly subscription billed through the Apple App Store.</li>
<li>Payment is charged to your Apple ID account at confirmation of purchase.</li>
<li>Subscriptions automatically renew unless cancelled at least 24 hours before the end of the current period.</li>
<li>You can manage or cancel subscriptions in your device Settings &gt; Subscriptions.</li>
</ul>
<h2>Account</h2>
<p>You are responsible for maintaining the security of your account credentials. You may delete your account at any time from the Profile tab.</p>
<h2>Limitation of Liability</h2>
<p>AI Caddie is provided "as is" without warranties. We are not liable for any decisions made based on AI recommendations.</p>
<h2>Changes</h2>
<p>We may update these terms at any time. Continued use of the app constitutes acceptance of updated terms.</p>
<h2>Contact</h2>
<p>Questions? Email us at <a href="mailto:support@caiddie.com">support@caiddie.com</a>.</p>
</body></html>`;

const SUPPORT = `<!DOCTYPE html><html><head><title>Support – AI Caddie</title>${PAGE_STYLE}</head><body>
<h1>AI Caddie Support</h1>
<p>Need help? We're here for you.</p>
<h2>Common Questions</h2>
<h3>How do I subscribe?</h3>
<p>Open the app and tap any premium feature (Club Recommendations, Course Strategy, or My Clubs). The subscription screen will appear where you can subscribe.</p>
<h3>How do I cancel my subscription?</h3>
<p>Go to your device Settings &gt; Apple ID &gt; Subscriptions, find AI Caddie, and tap Cancel.</p>
<h3>How do I restore my subscription on a new device?</h3>
<p>Go to the Profile tab and tap "Subscribe or restore", then tap "Restore purchases".</p>
<h3>How do I delete my account?</h3>
<p>Go to the Profile tab and tap "Delete Account". This permanently removes all your data.</p>
<h2>Contact Us</h2>
<p>For any other questions or issues, email us at <a href="mailto:support@caiddie.com">support@caiddie.com</a>.</p>
</body></html>`;

const PAGES: Record<string, string> = {
  '/privacy': PRIVACY,
  '/terms': TERMS,
  '/support': SUPPORT,
};

Deno.serve(async (req) => {
  const url = new URL(req.url);
  const rawPath = url.pathname;

  let page: string | undefined;
  if (rawPath.includes('/privacy')) page = PAGES['/privacy'];
  else if (rawPath.includes('/terms')) page = PAGES['/terms'];
  else if (rawPath.includes('/support')) page = PAGES['/support'];

  if (page) {
    return new Response(page, {
      status: 200,
      headers: new Headers({
        'content-type': 'text/html; charset=utf-8',
        'x-content-type-options': 'nosniff',
      }),
    });
  }

  return new Response('Not found', { status: 404 });
});
